export type ProductVariant = {
    weight: number; // in grams
    price: number;
    originalPrice?: number;
};

export type ProductImage = {
    type: 'hero' | 'lifestyle' | 'macro' | 'additional';
    url: string;
    alt: string;
    caption?: string;
};

export type ProductBenefit = {
    icon?: string;
    title: string;
    description: string;
};

export type Product = {
    id: string;
    name: string;
    price: number; // base/starting price
    originalPrice?: number;
    image: string; // Primary image (backward compatible)
    category: string;
    description: string;
    detailedDescription?: string;
    weightMl?: string; // weight or volume (e.g., '500g', '250ml')
    sku?: string;
    variants?: ProductVariant[]; // weight-based variants with prices

    // NEW: Rich Content for Premium UX
    painPointHeadline?: string; // Benefit-driven headline addressing customer pain
    sensoryDescription?: string; // 150-word rich description with lifestyle context
    benefits?: ProductBenefit[]; // Scannable value propositions
    images?: ProductImage[]; // Multi-image gallery (Hero, Lifestyle, Macro)

    // NEW: Conversion & Social Proof
    stockLevel?: 'in-stock' | 'low-stock' | 'out-of-stock';
    stockCount?: number;
    trustBadges?: string[]; // e.g., ['lab-tested', 'organic', 'free-shipping']
    frequentlyBoughtWith?: string[]; // Product IDs for cross-sell
    averageRating?: number;
    reviewCount?: number;
};

export const products: Product[] = [
    {
        id: 'choco-almond-rocks',
        name: 'Choco Almond Rocks',
        price: 650,
        image: '/products/choco-almond-rocks.png',
        category: 'Nuts',
        description: "Premium quality Choco Almond Rocks from Jehlum Kesar Co.",
        detailedDescription: "Description Choco Almond Rocks Choco Almond Rocks are a delightful fusion of crunchy premium almonds and rich, velvety chocolate , crafted into irresistible bite-sized clusters. Each rock delivers the perfect balance of nutty crunch and smooth chocolate indulgence , making it a treat you’ll keep coming back to. Made using high-quality almonds and premium chocolate , these rocks are ideal for satisfying sweet cravings while enjoying the goodness of nuts. Why Choose Choco Almond Rocks? 🍫 Rich, premium chocolate coating 🌰 Crunchy roasted almonds inside 😋 Perfect balance of sweet & nutty ✨ Premium quality & indulgent taste 🎁 Ideal for gifting & celebrations Perfect For Everyday indulgence Festive gifting & hampers Dessert toppings & party treats Tea-time & special occasions Enjoy Choco Almond Rocks as a luxury snack or sweet treat —a little crunch, a lot of chocolate, and pure happiness in every bite.",
        weightMl: '500g',
        painPointHeadline: "Craving Something Sweet? Indulge Without the Guilt",
        sensoryDescription: "Unwrap one and feel its weight—dense, satisfying. Bite down and hear that perfect crack as premium chocolate shell gives way to crunchy roasted almond inside. The chocolate is smooth, not overly sweet, with a deep cocoa richness that coats your tongue. The almond adds a nutty earthiness and satisfying crunch. These aren't mass-produced treats—each cluster is carefully crafted to deliver the perfect chocolate-to-nut ratio. Keep a jar on your desk for those 3 PM cravings, serve them at parties, or gift them to someone who deserves a premium treat.",
        benefits: [
            { icon: "🍫", title: "Premium Chocolate", description: "Rich cocoa coating, not overly sweet" },
            { icon: "🌰", title: "Whole Roasted Almonds", description: "Crunchy centers, nutrient-rich" },
            { icon: "🎁", title: "Gift-Worthy", description: "Perfect for celebrations and hampers" },
            { icon: "😋", title: "Balanced Indulgence", description: "Satisfying without being heavy" },
        ],
        images: [
            { type: 'hero', url: '/products/choco-almond-rocks.png', alt: 'Choco Almond Rocks in decorative jar' },
            { type: 'lifestyle', url: '/products/choco-almond-rocks-lifestyle.png', alt: 'Choco Almond Rocks served at tea time' },
            { type: 'macro', url: '/products/choco-almond-rocks-macro.png', alt: 'Close-up showing chocolate and almond' },
        ],
        stockLevel: 'in-stock',
        stockCount: 42,
        trustBadges: ['premium-quality', 'handcrafted', 'gift-ready'],
        frequentlyBoughtWith: ['dried-kiwi', 'acacia-honey'],
        averageRating: 4.6,
        reviewCount: 73,
    },
    {
        id: 'dried-kiwi',
        name: 'Dried Kiwi',
        price: 1000,
        image: '/products/dried-kiwi.png',
        category: 'Nuts',
        description: "Premium quality Dried Kiwi from Jehlum Kesar Co.",
        detailedDescription: "Description Dried Kiwi Dried Kiwi is a deliciously tangy and naturally sweet dried fruit , carefully dehydrated to preserve the vibrant color, tropical flavor, and essential nutrients of fresh kiwi. Soft, chewy, and refreshing, it makes a perfect healthy snack for all ages. Rich in vitamin C, fiber, and antioxidants , dried kiwi supports immunity, digestion, and overall wellness while satisfying sweet cravings in a natural way. Why Choose Dried Kiwi? 🥝 Naturally dried for rich flavor 💚 High in Vitamin C & antioxidants 🌿 No artificial colors or preservatives 😋 Soft, chewy & refreshing taste ✨ Premium quality fruit slices Health Benefits Boosts immunity Supports digestive health Promotes healthy skin Natural energy booster Perfect for snacking, breakfast bowls, baking, desserts, trail mixes, and gifting , Dried Kiwi adds a refreshing twist of flavor and nutrition to your day.",
        weightMl: '1kg',
        variants: [
            { weight: 1000, price: 1000 },
            { weight: 500, price: 500 },
        ],
        painPointHeadline: "Missing Tropical Flavors? Get Your Vitamin C Fix Naturally",
        sensoryDescription: "Pull out a slice and notice its vibrant green color—nature's candy preserved. The texture is soft and chewy, not sticky, with a concentrated kiwi flavor that's both sweet and tangy. Each bite delivers that distinctive tropical taste without overwhelming sugariness. These aren't your typical dried fruits—they're carefully dehydrated to preserve maximum nutrients and natural color. Pop a few as a mid-day snack, toss them in your morning yogurt, or pack them for your kids' lunchboxes. They're proof that healthy can be delicious.",
        benefits: [
            { icon: "🥝", title: "Vitamin C Powerhouse", description: "Boosts immunity naturally" },
            { icon: "💚", title: "Natural Energy", description: "Perfect pre-workout snack" },
            { icon: "🌿", title: "No Preservatives", description: "Just pure dried fruit" },
            { icon: "😋", title: "Tangy-Sweet Taste", description: "Addictively delicious" },
        ],
        images: [
            { type: 'hero', url: '/products/dried-kiwi.png', alt: 'Bright green dried kiwi slices' },
            { type: 'lifestyle', url: '/products/dried-kiwi-lifestyle.png', alt: 'Dried kiwi in yogurt bowl' },
            { type: 'macro', url: '/products/dried-kiwi-macro.png', alt: 'Close-up of kiwi slice texture' },
        ],
        stockLevel: 'in-stock',
        stockCount: 56,
        trustBadges: ['no-preservatives', 'vitamin-rich', 'kid-friendly'],
        frequentlyBoughtWith: ['cherry', 'choco-almond-rocks'],
        averageRating: 4.5,
        reviewCount: 48,
    },
    {
        id: 'cherry',
        name: 'Dried Cherry',
        price: 1400,
        image: '/products/cherry.png',
        category: 'Nuts',
        description: "Premium quality Dried Cherry from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Dried Cherry is a naturally sun-dried premium fruit , made from handpicked cherries grown in the cool valleys of Kashmir. Carefully dried to preserve their deep red color, tangy-sweet flavor, and rich nutritional value , these cherries are a delicious and healthy treat. Free from artificial colors and preservatives, Kashmiri dried cherries retain their natural antioxidants, vitamins, and minerals , making them perfect for both snacking and culinary use. Why Choose Kashmiri Dried Cherry? 🍒 Authentic Kashmiri origin ☀️ Naturally sun-dried 😋 Perfect balance of sweet & tangy taste 🌿 No artificial colors or preservatives ✨ Premium quality & rich flavor Health Benefits Rich in antioxidants for immunity Supports heart & joint health Aids digestion Natural energy booster Ideal for healthy snacking, baking, desserts, salads, cereals, and gifting , Kashmiri Dried Cherry brings the pure taste of Kashmir to every bite.",
        weightMl: '1kg',
        variants: [
            { weight: 1000, price: 1400 },
            { weight: 500, price: 700 },
        ],
        painPointHeadline: "Want Antioxidants Without Pills? Enjoy Nature's Candy",
        sensoryDescription: "These deep ruby-red cherries are sun-dried to perfection—chewy, not hard, with an intense cherry flavor that's both tart and sweet. Unlike mass-produced varieties, these are from Kashmir's cool valleys where cherries develop complex flavors. Pop one in your mouth and taste the concentrated essence of summer cherries. The natural tartness balances the sweetness perfectly. Add them to trail mixes, bake them into bread, or enjoy them straight from the bag. They're nature's way of making health taste indulgent.",
        benefits: [
            { icon: "🍒", title: "Rich in Antioxidants", description: "Fights free radicals naturally" },
            { icon: "☀️", title: "Sun-Dried", description: "Traditional method preserves nutrients" },
            { icon: "❤️", title: "Heart Healthy", description: "Supports cardiovascular wellness" },
            { icon: "✨", title: "Premium Kashmir", description: "Single-origin quality" },
        ],
        images: [
            { type: 'hero', url: '/products/cherry.png', alt: 'Deep red Kashmiri dried cherries' },
            { type: 'lifestyle', url: '/products/cherry-lifestyle.png', alt: 'Cherries in trail mix' },
            { type: 'macro', url: '/products/cherry-macro.png', alt: 'Close-up showing natural texture' },
        ],
        stockLevel: 'in-stock',
        stockCount: 38,
        trustBadges: ['sun-dried', 'antioxidant-rich', 'no-preservatives'],
        frequentlyBoughtWith: ['dried-kiwi', 'mix-dry-fruits'],
        averageRating: 4.6,
        reviewCount: 52,
    },
    {
        id: 'macadamia-nuts-in-shell',
        name: 'Macadamia Nuts In Shell',
        price: 3000,
        image: '/products/macadamia-nuts-in-shell.png',
        category: 'Nuts',
        description: "Premium quality Macadamia Nuts In Shell from Jehlum Kesar Co.",
        detailedDescription: "Description Macadamia Nuts In Shell (Premium Whole Nuts) Macadamia Nuts In Shell are luxury-grade whole nuts , naturally protected inside their hard shell to lock in freshness, flavor, and nutrition . Known for their rich, buttery taste and smooth crunch , macadamias are among the most premium and nutritious nuts in the world. Keeping them in shell helps preserve their natural oils and quality , ensuring you enjoy the nut at its freshest once cracked. Why Choose Macadamia Nuts In Shell? 🥜 Naturally protected for longer freshness 🧈 Rich, buttery flavor with premium texture 💪 High in healthy monounsaturated fats 🌿 No processing, no additives ✨ Premium quality whole nuts Health Benefits Supports heart health Boosts energy & metabolism Rich in antioxidants, minerals & good fats Helps maintain skin & hair health Ideal for healthy snacking, gourmet cooking, gifting, or roasting at home , Macadamia Nuts In Shell offer a pure, premium nut experience straight from nature.",
        weightMl: '400g',
        painPointHeadline: "Tired of Ordinary Nuts? Experience Buttery Luxury",
        sensoryDescription: "Crack open the shell and you'll understand why macadamias are the king of nuts. The meat inside is creamy-white, almost buttery in texture. Bite down and experience that signature crunch followed by a rich, slightly sweet, buttery flavor that lingers. These aren't pre-shelled—keeping them in their natural shell preserves freshness and that premium taste. Yes, they take effort to crack, but that's part of the ritual. Roast them lightly or enjoy them raw. They're worth every bit of effort for that incomparable taste and nutrition.",
        benefits: [
            { icon: "🧈", title: "Buttery Rich Flavor", description: "Creamiest nut texture you'll taste" },
            { icon: "❤️", title: "Heart-Healthy Fats", description: "Monounsaturated fats for wellness" },
            { icon: "🥜", title: "Shell-Protected Freshness", description: "Maximum flavor preservation" },
            { icon: "💎", title: "Luxury Grade", description: "Premium whole nuts" },
        ],
        images: [
            { type: 'hero', url: '/products/macadamia-nuts-in-shell.png', alt: 'Whole macadamia nuts in shell' },
            { type: 'lifestyle', url: '/products/macadamia-nuts-lifestyle.png', alt: 'Cracked macadamia nuts' },
            { type: 'macro', url: '/products/macadamia-nuts-macro.png', alt: 'Close-up of creamy nut interior' },
        ],
        stockLevel: 'in-stock',
        stockCount: 18,
        trustBadges: ['premium-grade', 'whole-nuts', 'natural'],
        frequentlyBoughtWith: ['kashmiri-mamra-badam', 'walnut-oil'],
        averageRating: 4.8,
        reviewCount: 31,
    },
    {
        id: 'beetroot-lip-butter',
        name: 'Beetroot Lip Butter',
        price: 375,
        image: '/products/beetroot-lip-butter.png',
        category: 'Beauty',
        description: "Premium quality Beetroot Lip Butter from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Beetroot Lip Butter Kashmiri Beetroot Lip Butter is a natural, nourishing lip care essential infused with the goodness of fresh Kashmiri beetroot extracts and rich plant-based butters . Specially crafted to moisturize and revive dry lips, it delivers a soft natural pink tint while keeping lips healthy, smooth, and supple. Packed with antioxidants and vitamins , beetroot helps enhance the natural lip color and protects against dullness, making this lip butter perfect for everyday use. Key Benefits 💋 Deeply moisturizes & repairs dry lips 🌸 Gives a natural rosy tint 🌿 Beetroot-infused for lip brightening 🛡️ Protects from dryness & chapping 🚫 Free from parabens, petroleum & harsh chemicals Natural Ingredients Kashmiri beetroot extract Shea butter / cocoa butter Natural oils (almond, coconut, or jojoba) Vitamin E Perfect for daily wear, overnight lip care, and all seasons , Kashmiri Beetroot Lip Butter adds a touch of natural color with deep nourishment—pure, gentle, and beautifully Kashmiri.",
        weightMl: '15ml',
        painPointHeadline: "Dry, Chapped Lips? Nourish with Natural Beetroot Magic",
        sensoryDescription: "Swipe this on and feel instant relief—the texture is creamy, not greasy, melting into your lips like butter. The subtle beetroot tint gives a natural flush of color, no artificial dyes. Smell the faint earthy sweetness of real beetroot extract mixed with nourishing oils. Within minutes, your lips feel softer, smoother. The color is sheer enough for everyday wear but buildable for a bolder look. This isn't just lip balm—it's lip treatment that actually works.",
        benefits: [
            { icon: "💋", title: "Natural Tint", description: "Subtle beetroot color, no chemicals" },
            { icon: "💧", title: "Deep Hydration", description: "Locks in moisture for hours" },
            { icon: "🌿", title: "All-Natural", description: "No parabens or artificial colors" },
            { icon: "✨", title: "Dual-Purpose", description: "Treatment & color in one" },
        ],
        images: [
            { type: 'hero', url: '/products/beetroot-lip-butter.png', alt: 'Kashmiri Beetroot Lip Butter jar' },
        ],
        stockLevel: 'in-stock',
        stockCount: 67,
        trustBadges: ['all-natural', 'paraben-free', 'cruelty-free'],
        frequentlyBoughtWith: ['rose-water', 'saffron-lip-butter'],
        averageRating: 4.7,
        reviewCount: 94,
    },
    {
        id: 'rosemary-essential-oil',
        name: 'Rosemary Essential Oil',
        price: 1499,
        image: '/products/rosemary-essential-oil.png',
        category: 'Beauty',
        description: "Premium quality Rosemary Essential Oil from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri rose essence typically refers to essential oil extracted from high-quality rose petals, especially varieties like Rosa damascena grown in Kashmir’s cool climate — known for its rich aroma and therapeutic qualities . Benefits of rose essential oil include: 🌸 Calming & stress relief — inhaling its scent is soothing. 🧘‍♀️ Aromatherapy & mood enhancement — adds warmth and relaxation to diffusers. 💆‍♀️ Skin benefits (when diluted) — can help soothe inflammation, promote hydration, and revitalize skin tone",
        weightMl: '15ml',
        painPointHeadline: "Stressed? Breathe in Calming Rosemary Aromatherapy",
        sensoryDescription: "Uncap the bottle and that sharp, herbaceous aroma fills the air—instantly clarifying, energizing. A single drop on your temples or in a diffuser transforms your space. This isn't diluted—it's pure essential oil, potent and therapeutic. Use it for scalp massage to stimulate hair growth, or add to your bath for muscle relaxation. The scent is grounding yet uplifting, perfect for focus during work or unwinding after a long day.",
        benefits: [
            { icon: "🧘", title: "Stress Relief", description: "Calming aromatherapy for mind & body" },
            { icon: "💆", title: "Hair Growth", description: "Stimulates scalp circulation" },
            { icon: "🧠", title: "Mental Clarity", description: "Enhances focus and concentration" },
            { icon: "✅", title: "100% Pure", description: "Therapeutic-grade essential oil" },
        ],
        images: [
            { type: 'hero', url: '/products/rosemary-essential-oil.png', alt: 'Pure rosemary essential oil bottle' },
            { type: 'lifestyle', url: '/products/rosemary-essential-oil-lifestyle.png', alt: 'Rosemary oil in diffuser' },
            { type: 'macro', url: '/products/rosemary-essential-oil-macro.png', alt: 'Oil drop close-up' },
        ],
        stockLevel: 'in-stock',
        stockCount: 45,
        trustBadges: ['100-pure', 'therapeutic-grade', 'organic'],
        frequentlyBoughtWith: ['rose-water', 'walnut-oil'],
        averageRating: 4.6,
        reviewCount: 37,
    },
    {
        id: 'saffron-lip-butter',
        name: 'Saffron Lip Butter',
        price: 375,
        image: '/products/saffron-lip-butter.png',
        category: 'Saffron',
        description: "Premium quality Saffron Lip Butter from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Saffron Lip Butter Kashmiri Saffron Lip Butter is a luxurious, natural lip care product made with premium Kashmiri saffron and nourishing botanical butters . This rich, creamy formula hydrates, softens, and protects your lips while delivering the antioxidant and soothing benefits of saffron . Crafted with gentle, skin-loving ingredients, it’s perfect for daily use to keep your lips smooth, supple, and naturally radiant — especially in dry or cold climates like Kashmir’s. Key Benefits 💋 Deep hydration & nourishment — keeps lips soft and healthy 🌿 Saffron-infused — helps brighten and rejuvenate 🛡️ Protects against dryness & cracking 🍯 Natural and gentle — free from harsh chemicals 🪄 Light, luxurious texture — non-sticky and smooth Typical Ingredients Kashmiri saffron (rich in antioxidants) Shea butter / cocoa butter (for deep moisture) Natural oils (like coconut, almond, jojoba) Vitamin E (for repair and protection) Use it as a daily lip balm, especially before sleep or outdoor activities , for irresistibly soft and healthy lips.",
        weightMl: '10g',
        painPointHeadline: "Want Naturally Radiant Lips? Try Saffron's Golden Touch",
        sensoryDescription: "This luxurious butter has a hint of saffron's golden glow. Apply it and feel your lips soften instantly. The saffron extract works overnight to brighten and rejuvenate while butters lock in moisture. Wake up to naturally healthier, more radiant lips. The texture is rich without being heavy, absorbing quickly. Use it before bed for intensive repair or during the day for a subtle, healthy sheen.",
        benefits: [
            { icon: "🌸", title: "Saffron-Infused", description: "Natural brightening & rejuvenation" },
            { icon: "💧", title: "Deep Nourishment", description: "Long-lasting moisture lock" },
            { icon: "🌿", title: "Natural Ingredients", description: "Gentle, chemical-free formula" },
            { icon: "🌙", title: "Overnight Repair", description: "Wake up to softer lips" },
        ],
        images: [
            { type: 'hero', url: '/products/saffron-lip-butter.png', alt: 'Kashmiri Saffron Lip Butter jar' },
        ],
        stockLevel: 'in-stock',
        stockCount: 52,
        trustBadges: ['saffron-infused', 'all-natural', 'gentle-formula'],
        frequentlyBoughtWith: ['kashmiri-saffron', 'beetroot-lip-butter'],
        averageRating: 4.8,
        reviewCount: 68,
    },
    {
        id: 'white-oud',
        name: 'White Oud',
        price: 1649,
        image: '/products/white-oud.png',
        category: 'Fragrance',
        description: "Premium quality White Oud from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmir White Oud (Premium Fragrance Essence) Kashmir White Oud is a rare and refined aromatic treasure , admired for its soft, clean, and slightly sweet woody fragrance . Lighter and more delicate than traditional dark oud, White Oud offers a smooth, calming scent that feels elegant, fresh, and luxurious. Sourced and prepared with great care, this premium oud is ideal for those who prefer a subtle yet long-lasting aroma . It is widely used in perfumery, incense burning, meditation, and spiritual rituals , creating an atmosphere of peace and sophistication. Why Choose Kashmir White Oud? 🤍 Soft, clean & elegant oud fragrance 🌿 Light woody notes with gentle sweetness 🕯️ Perfect for daily use, meditation & prayer 👑 Premium quality with lasting aroma 🚫 No synthetic fragrance or chemicals Perfect for personal fragrance, calm indoor ambiance, or thoughtful gifting , Kashmir White Oud reflects purity, grace, and timeless Kashmiri luxury.",
        weightMl: '7ml',
        painPointHeadline: "Subtle Elegance? Try White Oud",
        sensoryDescription: "Delicate and refined. Soft woody notes with gentle sweetness. Elegant without overpowering, perfect for daily wear or meditation. Calming, peaceful atmosphere.",
        benefits: [
            { icon: "🤍", title: "Soft", description: "Refined fragrance" },
            { icon: "🌿", title: "Light", description: "Gentle sweetness" },
            { icon: "🕯️", title: "Meditation", description: "Peaceful" },
            { icon: "✨", title: "Daily", description: "Subtle" },
        ],
        images: [
            { type: 'hero', url: '/products/white-oud.png', alt: 'Premium White Oud fragrance bottle' },
            { type: 'lifestyle', url: '/products/white-oud-lifestyle.png', alt: 'White Oud in meditation setting' },
        ],
        stockLevel: 'in-stock',
        stockCount: 12,
        trustBadges: ['premium-quality'],
        frequentlyBoughtWith: ['golden-oud'],
        averageRating: 4.7,
        reviewCount: 19,
    },
    {
        id: 'golden-oud',
        name: 'Golden Oud',
        price: 1599,
        image: '/products/golden-oud.png',
        category: 'Fragrance',
        description: "Premium quality Golden Oud from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmir Golden Oud (Premium Fragrance Essence) Kashmir Golden Oud is a rare and luxurious aromatic treasure , known for its deep, warm, woody, and slightly sweet fragrance . Carefully sourced and refined, this premium oud captures the essence of timeless elegance and spiritual richness associated with Kashmir’s heritage. Highly prized in perfumery and traditional rituals, Golden Oud is cherished for its long-lasting aroma, calming effect, and royal character . Just a small amount releases a rich scent that lingers beautifully, making it a symbol of luxury and purity. Why Choose Kashmir Golden Oud? 🌟 Premium-grade, rich oud aroma 🌿 Deep woody, warm & elegant fragrance 🕯️ Ideal for incense, perfumery & meditation 👑 Luxurious & long-lasting scent 🚫 Free from synthetic additives Perfect for personal fragrance use, spiritual rituals, meditation, or gifting , Kashmir Golden Oud offers an experience of refined luxury and soulful calm—straight from the heart of Kashmir.",
        weightMl: '7ml',
        painPointHeadline: "Stand Out with Luxury Oud",
        sensoryDescription: "One drop envelops you in woody, sweet aroma. Lingers for hours, evolving. Scent of royalty, mysterious and captivating. Apply to pulse points and let it develop.",
        benefits: [
            { icon: "👑", title: "Long-Lasting", description: "8+ hours" },
            { icon: "🌟", title: "Premium", description: "Rare quality" },
            { icon: "🎭", title: "Natural", description: "No synthetics" },
            { icon: "✨", title: "Unisex", description: "For all" },
        ],
        images: [
            { type: 'hero', url: '/products/golden-oud.png', alt: 'Premium Golden Oud fragrance bottle' },
            { type: 'lifestyle', url: '/products/golden-oud-lifestyle.png', alt: 'Golden Oud in elegant setting' },
        ],
        stockLevel: 'low-stock',
        stockCount: 6,
        trustBadges: ['premium-grade'],
        frequentlyBoughtWith: ['rose-water'],
        averageRating: 4.9,
        reviewCount: 24,
    },
    {
        id: 'acacia-honey',
        name: 'Acacia Honey',
        price: 1050,
        image: '/products/acacia-honey.png',
        category: 'Honey',
        description: "Premium quality Acacia Honey from Jehlum Kesar Co.",
        detailedDescription: "Description Acacia Honey Pure, light, and naturally refined — Acacia Honey is prized for its crystal-clear appearance, silky texture, and delicate floral sweetness. Sourced from the nectar of acacia blossoms, this premium honey is naturally slow to crystallize and loved for its clean, mild taste. Rich in natural antioxidants and gentle on digestion, acacia honey is an ideal everyday sweetener. Its subtle flavor makes it perfect for tea, warm water, desserts, salad dressings, and drizzling over fruits or yogurt without overpowering other ingredients. Why you’ll love it: 🌼 Light, mild & naturally sweet 🍯 Slow to crystallize, smooth texture 🌿 100% pure & naturally sourced ☕ Perfect for tea, desserts & daily use A simple, elegant honey — pure nature in every drop. 🍯✨",
        weightMl: '500ml',
        painPointHeadline: "Why Sugar? Have Liquid Gold",
        sensoryDescription: "Crystal-clear, silky texture like molten amber. Acacia is delicate—floral sweetness that enhances not overpowers. Stays smooth and pourable for months.",
        benefits: [
            { icon: "🍯", title: "Slow Crystallize", description: "Stays smooth" },
            { icon: "🌼", title: "Mild Floral", description: "Perfect for tea" },
            { icon: "🌿", title: "Pure", description: "No additives" },
            { icon: "💚", title: "Gentle", description: "Low glycemic" },
        ],
        images: [
            { type: 'hero', url: '/products/acacia-honey.png', alt: 'Pure Acacia Honey in glass jar' },
        ],
        stockLevel: 'in-stock',
        stockCount: 23,
        trustBadges: ['100-pure'],
        frequentlyBoughtWith: ['kashmiri-saffron'],
        averageRating: 4.7,
        reviewCount: 64,
    },
    {
        id: 'gulkhand',
        name: 'Gulkhand',
        price: 550,
        image: '/products/gulkhand.webp',
        category: 'Kashmiri Special',
        description: "Premium quality Gulkhand from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Gulkhand (Rose Petal Preserve) Kashmiri Gulkhand is a traditional Ayurvedic delicacy made from handpicked Kashmiri rose petals , slowly preserved with natural sweeteners to retain their aroma, flavor, and therapeutic benefits. Prepared using age-old methods, this gulkhand is pure, chemical-free, and richly fragrant . Known for its cooling properties , Kashmiri Gulkhand helps balance body heat, supports digestion, boosts energy, and promotes overall wellness. Its naturally sweet taste and soft texture make it both delicious and medicinal . Why Choose Kashmiri Gulkhand? 🌹 Made from premium Kashmiri rose petals ❄️ Natural body coolant 🌿 Aids digestion & gut health 💖 Supports heart & skin health 🚫 No artificial colors, flavors, or preservatives Enjoy Kashmiri Gulkhand directly by the spoon, mixed with milk, added to desserts, or used in traditional drinks —a timeless taste of Kashmir’s natural purity.",
        weightMl: '500g',
        painPointHeadline: "Why Suffer from Heat? Cool Down with Royal Rose Preserve",
        sensoryDescription: "Open the jar and the fragrance of a thousand rose petals greets you—sweet, floral, utterly captivating. Scoop out this ruby-red preserve and notice the soft, jam-like texture studded with visible rose petals. The taste is a perfect harmony of natural sweetness and delicate rose essence. In Ayurveda, Gulkhand is hailed as a natural coolant, perfect for hot summers or after spicy meals. Take a spoonful directly, mix it into milk, or spread it on bread. Feel the cooling sensation.",
        benefits: [
            { icon: "❄️", title: "Natural Body Coolant", description: "Balances body heat, perfect for summer" },
            { icon: "🌹", title: "Handpicked Rose Petals", description: "Premium Kashmiri roses only" },
            { icon: "🌿", title: "Aids Digestion", description: "Supports gut health naturally" },
            { icon: "💖", title: "Skin & Heart Health", description: "Rich in antioxidants" },
        ],
        images: [
            { type: 'hero', url: '/products/gulkhand.png', alt: 'Gulkhand rose petal preserve' },
            { type: 'lifestyle', url: '/products/gulkhand-lifestyle.png', alt: 'Gulkhand served with milk' },
        ],
        stockLevel: 'in-stock',
        stockCount: 28,
        trustBadges: ['traditional-recipe', 'no-preservatives', 'organic'],
        frequentlyBoughtWith: ['acacia-honey', 'shahi-kehwa'],
        averageRating: 4.5,
        reviewCount: 38,
    },
    {
        id: 'kashmiri-mamra-badam',
        name: 'Kashmiri Mamra Badam',
        price: 1100,
        image: '/products/kashmiri-mamra-badam.png',
        category: 'Other',
        description: "Premium quality Kashmiri Mamra Badam from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Mamra Badam (Premium Almonds) Kashmiri Mamra Badam are naturally grown, premium almonds sourced from the pristine valleys of Kashmir. Unlike regular almonds, Mamra Badam are small, irregular in shape, and rich in natural oil , which makes them more nutritious and flavorful. These almonds are 100% natural, non-polished, and chemical-free , retaining their original taste and health benefits. Highly valued in Ayurveda, Mamra Badam are known for boosting brain health, immunity, energy, and overall vitality . Why Choose Kashmiri Mamra Badam? 🌰 Authentic Kashmiri origin 💪 High in healthy fats, protein & antioxidants 🧠 Supports brain & memory health 🌱 Naturally grown, no artificial processing ✨ Rich taste with crunchy texture Perfect for daily consumption, soaking overnight, or gifting , Kashmiri Mamra Badam are a true symbol of purity and wellness.",
        weightMl: '500g',
        sku: 'CBM22',
        variants: [
            { weight: 500, price: 1100 },
        ],
        painPointHeadline: "Forget Regular Almonds—Try the Ayurvedic Powerhouse",
        sensoryDescription: "These aren't your typical almonds. Mamra Badam are smaller, irregular in shape, but packed with natural oils that give them an incredibly rich, almost buttery flavor. Soak them overnight and peel off the skin—the texture is creamy, the taste intensely nutty. Ayurveda treasures these for brain health and vitality. Each bite delivers dense nutrition that regular almonds simply can't match. These are the almonds grandmothers recommend for sharp memory.",
        benefits: [
            { icon: "🧠", title: "Brain Health Booster", description: "Ayurvedic treasure for memory & focus" },
            { icon: "🌰", title: "High Natural Oils", description: "Richer, more nutritious than regular almonds" },
            { icon: "⚡", title: "Energy & Vitality", description: "Packed with protein and healthy fats" },
            { icon: "✨", title: "Premium Kashmir", description: "Authentic Mamra variety" },
        ],
        images: [
            { type: 'hero', url: '/products/kashmiri-mamra-badam.png', alt: 'Kashmir Mamra Badam almonds' },
            { type: 'lifestyle', url: '/products/kashmiri-mamra-badam-lifestyle.png', alt: 'Soaked almonds' },
            { type: 'macro', url: '/products/kashmiri-mamra-badam-macro.png', alt: 'Close-up showing oil-rich texture' },
        ],
        stockLevel: 'in-stock',
        stockCount: 29,
        trustBadges: ['ayurvedic', 'premium-grade', 'natural'],
        frequentlyBoughtWith: ['macadamia-nuts-in-shell', 'walnut-oil'],
        averageRating: 4.8,
        reviewCount: 76,
    },
    {
        id: 'kashmiri-saffron',
        name: 'Kashmiri Saffron',
        price: 350,
        image: '/products/kashmiri-saffron-lifestyle.png',
        category: 'Saffron',
        description: "Premium quality Kashmiri Saffron from Jehlum Kesar Co.",
        detailedDescription: "Description The Red Gold of Kashmir Indulge in the luxury of authentic Kashmiri Saffron. Unlike other varieties, Kashmiri Kesar is prized for having the highest levels of Crocin (color), Picrocrocin (flavor), and Safranal (aroma). Our saffron is hand-harvested in the autumn chill of the Kashmir Valley. We laboriously separate the deep red stigmas (Mongra) from the flower to ensure you get only the most potent part of the spice. Just a few strands are enough to transform your culinary creations or beauty rituals. Why Choose Our Saffron? Single Origin: Sourced directly from local growers in Pampore. Lab Tested: Certified for purity and Grade A quality. Zero Adulteration: No artificial colors, no moisture weight, no floral waste. 4. Key Features & Benefits Use this for bullet points: Distinctive Aroma: A sweet, floral scent that instantly fills the room. Potent Color: Deep maroon strands that release a rich golden-yellow hue when soaked. Health Powerhouse: Rich in antioxidants; known to boost immunity, aid digestion, and support skin health. Pregnancy Safe: Pure and natural, making it a trusted choice for expectant mothers (consult a doctor). Versatile Use: Ideal for Kashmiri Kahwa , Biryani , Kheer , or face masks for glowing skin.",
        sku: 'CBM21',
        variants: [
            { weight: 1, price: 350 },
            { weight: 2, price: 700 },
            { weight: 5, price: 1750 },
            { weight: 10, price: 3500 },
            { weight: 20, price: 7000 },
            { weight: 25, price: 8750 },
            { weight: 50, price: 17500 },
        ],
        painPointHeadline: "Tired of Fake Saffron That Tastes Like Nothing?",
        sensoryDescription: "Open the jar and breathe in—that intoxicating aroma isn't an accident. Each crimson thread carries the essence of 150,000 hand-picked flowers, harvested at dawn when their oils are most potent. Feel the delicate, dry strands between your fingers—brittle yet precious. Drop them in warm milk and watch the alchemy: threads bloom into liquid gold, releasing a sweet, earthy fragrance that fills your kitchen. This is saffron as it was meant to be—so potent that 10-15 strands transform an entire dish.",
        benefits: [
            { icon: "✨", title: "Highest Potency", description: "3x the Crocin content—a little goes a long way" },
            { icon: "🧪", title: "Lab-Certified", description: "Zero adulterants, tested for authenticity" },
            { icon: "🤰", title: "Pregnancy-Safe", description: "Pure and natural, trusted by generations" },
            { icon: "👨‍🍳", title: "Chef-Approved", description: "Transforms biryani, kheer, and kahwa" },
        ],
        images: [
            { type: 'hero', url: '/products/kashmiri-saffron-lifestyle.png', alt: 'Saffron steeping in milk, releasing golden color' },
            { type: 'lifestyle', url: '/products/kashmiri-saffron.png', alt: 'Premium Kashmiri Saffron threads - deep crimson red' },
            { type: 'macro', url: '/products/kashmiri-saffron-macro.png', alt: 'Close-up showing quality stigmas' },
        ],
        stockLevel: 'in-stock',
        stockCount: 47,
        trustBadges: ['lab-tested', 'organic', 'single-origin'],
        frequentlyBoughtWith: ['shahi-kehwa', 'acacia-honey'],
        averageRating: 4.9,
        reviewCount: 127,
    },
    {
        id: 'mix-dry-fruits',
        name: 'Mix Dry Fruits',
        price: 750,
        image: '/products/mix-dry-fruits.png',
        category: 'Nuts',
        description: "Premium quality Mix Dry Fruits from Jehlum Kesar Co.",
        detailedDescription: "Description Premium Mix Dry Fruits Our Mix Dry Fruits is a carefully curated blend of premium-quality nuts and dried fruits , sourced for their freshness, taste, and nutritional value. This wholesome mix typically includes almonds, cashews, walnuts, raisins, pistachios, and other select dry fruits , offering the perfect balance of crunch, sweetness, and energy. Naturally rich in proteins, healthy fats, fiber, vitamins, and antioxidants , this mix is ideal for boosting immunity, improving digestion, and maintaining daily energy levels. Why Choose Our Mix Dry Fruits? 🌰 Handpicked premium dry fruits 💪 High in nutrition & natural energy 🌱 No artificial colors or preservatives 🧼 Hygienically cleaned & packed 🎁 Perfect for daily snacking & gifting Enjoy it as a healthy snack, breakfast topping, festive treat, or gift hamper essential —a delicious way to stay healthy every day.",
        weightMl: '500g',
        sku: 'CBM23',
        painPointHeadline: "Snacking Boring? Energize with Premium Nut Medley",
        sensoryDescription: "Open the bag and you get cashews, almonds, walnuts, raisins, pistachios—a symphony of textures and flavors. Each handful is different. The nuts are crunchy, the raisins sweet and chewy. Perfect for mid-day energy, pre-workout fuel, or just satisfying hunger healthily. No two handfuls taste the same. This is nature's perfect snack mix, carefully balanced for taste and nutrition.",
        benefits: [
            { icon: "💪", title: "Complete Nutrition", description: "Protein, healthy fats, vitamins in every handful" },
            { icon: "⚡", title: "Energy Boost", description: "Perfect pre-workout or midday fuel" },
            { icon: "🥜", title: "Variety Pack", description: "5+ premium nuts and fruits" },
            { icon: "🌿", title: "Clean & Natural", description: "No preservatives, hygienically packed" },
        ],
        images: [
            { type: 'hero', url: '/products/mix-dry-fruits.png', alt: 'Premium mix dry fruits assortment' },
            { type: 'lifestyle', url: '/products/mix-dry-fruits-lifestyle.png', alt: 'Dry fruits in snack bowl' },
            { type: 'macro', url: '/products/mix-dry-fruits-macro.png', alt: 'Close-up showing variety' },
        ],
        stockLevel: 'in-stock',
        stockCount: 63,
        trustBadges: ['no-preservatives', 'premium-mix', 'hygienically-packed'],
        frequentlyBoughtWith: ['cherry', 'dried-kiwi'],
        averageRating: 4.6,
        reviewCount: 91,
    },
    {
        id: 'rose-water',
        name: 'Rose Water',
        price: 375,
        image: '/products/rose-water.png',
        category: 'Beauty',
        description: "Premium quality Rose Water from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Rose Water Refresh your senses with pure Kashmiri Rose Water , carefully distilled from fresh handpicked roses grown in the serene valleys of Kashmir. Prepared using traditional steam-distillation methods, this rose water retains its natural floral aroma, purity, and soothing properties —free from alcohol, chemicals, and artificial fragrances. Renowned for its cooling, calming, and hydrating benefits , Kashmiri rose water is ideal for skin care, culinary use, and daily wellness rituals . Whether used as a natural facial toner, mixed in drinks and desserts, or applied for relaxation, it delivers gentle freshness and authentic quality. 🌹 Why Choose Kashmiri Rose Water? 100% pure & naturally distilled Made from fresh Kashmiri roses Alcohol-free, chemical-free & preservative-free Soothes skin, refreshes mind & cools the body Suitable for skincare, food & traditional use Experience timeless purity— soft, fragrant, and naturally refreshing , straight from Kashmir.",
        weightMl: '200ml',
        painPointHeadline: "Dull Skin? Refresh with Kashmiri Roses",
        sensoryDescription: "Spritz and smell a garden of roses—pure, delicate. Ultra-fine mist, cooling on contact. Your skin drinks it in, instantly hydrated. Nature's facial in a bottle.",
        benefits: [
            { icon: "🌹", title: "Pure Extract", description: "100% natural" },
            { icon: "💧", title: "Hydrates", description: "Balances pH" },
            { icon: "✨", title: "Multi-Use", description: "Toner, spray" },
            { icon: "❄️", title: "Cooling", description: "Calms skin" },
        ],
        images: [
            { type: 'hero', url: '/products/rose-water.png', alt: 'Pure Kashmiri Rose Water bottle' },
            { type: 'lifestyle', url: '/products/rose-water-lifestyle.png', alt: 'Rose water facial mist' },
        ],
        stockLevel: 'in-stock',
        stockCount: 72,
        trustBadges: ['100-pure'],
        frequentlyBoughtWith: ['beetroot-lip-butter'],
        averageRating: 4.7,
        reviewCount: 103,
    },
    {
        id: 'saffron-honey',
        name: 'Saffron Honey',
        price: 850,
        image: '/products/saffron-honey.png',
        category: 'Honey',
        description: "Premium quality Saffron Honey from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Saffron Honey Indulge in the royal richness of Kashmiri Saffron Honey , a rare blend of pure natural honey infused with authentic Kashmiri saffron (Kesar) . Crafted with care, this golden elixir combines the natural sweetness of raw honey with the delicate aroma, color, and wellness properties of hand-harvested saffron from Kashmir. Naturally rich in antioxidants and nutrients, Kashmiri saffron honey is known to boost immunity, improve digestion, enhance energy levels, and promote overall vitality . Its smooth texture and floral taste make it perfect for daily consumption, warm milk, herbal teas, desserts, or traditional remedies . 🍯 Why Choose Kashmiri Saffron Honey? Made with pure natural honey & authentic Kashmiri saffron No added sugar, chemicals, or preservatives Rich in antioxidants & immunity-boosting properties Enhances energy, digestion & overall wellness Ideal for daily use, gifting & traditional health routines Taste the luxury of Kashmir in every spoon— pure, aromatic, and naturally nourishing .",
        weightMl: '500g',
        painPointHeadline: "Immunity Boost with Saffron Honey",
        benefits: [{ icon: "🌸", title: "Saffron-Infused", description: "Rare blend" }],
        images: [
            { type: 'hero', url: '/products/saffron-honey.png', alt: 'Saffron-infused honey jar' },
        ],
        stockLevel: 'in-stock', stockCount: 19, trustBadges: ['saffron-infused'],
        frequentlyBoughtWith: ['kashmiri-saffron'], averageRating: 4.8, reviewCount: 51,
    },
    {
        id: 'shahi-heeing',
        name: 'Shahi Heeing',
        price: 860,
        image: '/products/shahi-heeing.png',
        category: 'Kashmiri Special',
        description: "Premium quality Shahi Heeing from Jehlum Kesar Co.",
        detailedDescription: "Description Rich, aromatic, and exceptionally potent — Shahi Heeng (Asafoetida) is a premium spice treasured for its strong flavor and powerful digestive benefits. Sourced and processed with care, this royal-grade heeng requires only a tiny pinch to transform everyday dishes with deep, authentic taste. Known for enhancing digestion and reducing bloating, Shahi Heeng is a staple in traditional Indian cooking. Its bold aroma mellows beautifully when cooked, adding depth to dals, curries, vegetables, and tempering without overpowering the dish. Why you’ll love it: 👑 Premium, high-potency quality 🌿 Pure & carefully processed 🍲 Enhances flavor with just a pinch 🌱 Supports digestion & gut health A little goes a long way — Shahi Heeng is the secret touch behind truly flavorful, wholesome meals. ✨🌿",
        weightMl: '300g',
        painPointHeadline: "Premium Asafoetida for Digestion",
        benefits: [{ icon: "🌿", title: "Pure", description: "High potency" }],
        images: [
            { type: 'hero', url: '/products/shahi-heeing.png', alt: 'Premium Shahi Heeing' },
        ],
        stockLevel: 'in-stock', stockCount: 30, trustBadges: ['premium-grade'],
        averageRating: 4.6, reviewCount: 25,
    },
    {
        id: 'shahi-kehwa',
        name: 'Shahi Kehwa',
        price: 375,
        image: '/products/shahi-kehwa.webp',
        category: 'Tea',
        description: "Premium quality Shahi Kehwa from Jehlum Kesar Co.",
        detailedDescription: "Description Shahi Kehwa A royal blend rooted in Kashmiri tradition, Shahi Kehwa is an aromatic green tea infused with exotic spices and precious saffron. This timeless beverage is known for its warm, soothing flavor and luxurious fragrance that reflects the rich heritage of the valley. Carefully crafted with green tea leaves, cardamom, cinnamon, almonds, and saffron, Shahi Kehwa is light on the palate yet deeply comforting. Traditionally enjoyed during cold mornings and special gatherings, it aids digestion, refreshes the body, and gently energizes the mind. Why you’ll love it: 👑 Royal Kashmiri heritage blend 🌸 Infused with saffron & aromatic spices 🍃 Light, soothing & refreshing ☕ Perfect for mornings & after meals A cup of Shahi Kehwa is not just tea — it’s a warm taste of Kashmir’s royal hospitality. 🍵✨",
        weightMl: '80g',
        sku: 'N/A',
        variants: [
            { weight: 80, price: 375 },
            { weight: 250, price: 1250 },
        ],
        painPointHeadline: "Tired of Ordinary Tea? Experience Royal Kashmiri Tradition",
        sensoryDescription: "Steep the blend and inhale—saffron threads unfurl in hot water, releasing their golden essence alongside cardamom, cinnamon, and crushed almonds. This isn't just tea; it's a centuries-old Kashmiri ritual reserved for royalty. Each sip delivers warmth that spreads from your chest outward, the spices dancing on your palate while saffron adds a subtle, exotic sweetness. The crushed almonds lend a delicate nuttiness. Traditionally served during cold Kashmiri mornings and festive gatherings.",
        benefits: [
            { icon: "👑", title: "Royal Heritage Blend", description: "Authentic saffron + aromatic spices" },
            { icon: "🍃", title: "Light & Refreshing", description: "Green tea base, gentle on stomach" },
            { icon: "🌸", title: "Saffron-Infused", description: "Premium Kashmiri saffron in every sip" },
            { icon: "☕", title: "Perfect After Meals", description: "Aids digestion, refreshes palate" },
        ],
        images: [
            { type: 'hero', url: '/products/shahi-kehwa.png', alt: 'Shahi Kehwa tea blend with saffron' },
            { type: 'lifestyle', url: '/products/shahi-kehwa-lifestyle.png', alt: 'Steaming cup of Shahi Kehwa' },
        ],
        stockLevel: 'in-stock',
        stockCount: 34,
        trustBadges: ['organic', 'traditional-recipe', 'free-shipping'],
        frequentlyBoughtWith: ['kashmiri-saffron', 'acacia-honey'],
        averageRating: 4.7,
        reviewCount: 56,
    },
    {
        id: 'shilajit',
        name: 'Shilajit',
        price: 1900,
        image: '/products/shilajit.png',
        category: 'Kashmiri Special',
        description: "Premium quality Shilajit from Jehlum Kesar Co.",
        detailedDescription: "Description Original Himalayan Shilajit Resin – 100% Purified & Sun-Dried. Reclaim Your Prime Energy. Feeling drained? It's time to tap into the ancient energy of the Himalayas. Our Kashmiri Shilajit is not a mass-produced powder; it is a raw, potent resin oozing with vitality. Sourced from the high-altitude rocks of Kashmir (16,000+ ft), this is nature's ultimate multivitamin. We use the traditional Surya Tapi (sun-drying) method, a slow process that takes weeks but preserves the delicate bioactive compounds that heat-processing destroys. The result? A pure, tar-like resin packed with Fulvic Acid and over 84 trace minerals. What It Does for You: Infinite Energy - Combats chronic fatigue and naturally boosts mitochondrial energy. Peak Performance - Supports muscle recovery, stamina, and strength. Mental Clarity - Clears brain fog and improves focus. The Purity Test: Our resin dissolves completely in warm water without leaving any residue—the hallmark of authentic, unadulterated Shilajit. How to Use: Using the included spoon, take a pea-sized amount (approx. 300-500mg). Dissolve it in warm water, milk, or green tea. Drink every morning on an empty stomach to fuel your day.",
        weightMl: '50g',
        variants: [
            { weight: 50, price: 1900 },
            { weight: 100, price: 3800 },
            { weight: 200, price: 7600 },
        ],
        painPointHeadline: "Feeling Drained? Reclaim Your Prime Energy",
        sensoryDescription: "Scoop out a pea-sized amount of this dark, tar-like resin and feel its sticky, mineral-rich texture. Dissolve it in warm water and watch it transform into an ancient elixir—earthy, slightly bitter, reminding you this is raw nature.",
        benefits: [
            { icon: "⚡", title: "Combat Fatigue", description: "Boosts energy naturally" },
            { icon: "💪", title: "Peak Performance", description: "Muscle recovery" },
            { icon: "🧠", title: "Mental Clarity", description: "Improves focus" },
            { icon: "🧪", title: "84 Minerals", description: "Rich in fulvic acid" },
        ],
        images: [
            { type: 'hero', url: '/products/shilajit.png', alt: 'Himalayan Shilajit resin jar' },
            { type: 'lifestyle', url: '/products/shilajit-lifestyle-1.png', alt: 'Shilajit dissolved in warm water' },
            { type: 'lifestyle', url: '/products/shilajit-lifestyle-2.png', alt: 'Shilajit serving preparation' },
            { type: 'lifestyle', url: '/products/shilajit-lifestyle-3.png', alt: 'Shilajit in daily ritual' },
            { type: 'macro', url: '/products/shilajit-macro.png', alt: 'Close-up of resin texture' },
            { type: 'additional', url: '/products/shilajit-banner.png', alt: 'Shilajit product banner' },
        ],
        stockLevel: 'low-stock',
        stockCount: 8,
        trustBadges: ['lab-tested', 'sun-dried'],
        frequentlyBoughtWith: ['kashmiri-saffron', 'acacia-honey'],
        averageRating: 4.8,
        reviewCount: 89,
    },
    {
        id: 'walnut-oil',
        name: 'Walnut Oil',
        price: 650,
        image: '/products/walnut-oil.png',
        category: 'Nuts',
        description: "Premium quality Walnut Oil from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Walnut Oil Discover the purity of cold-pressed Kashmiri Walnut Oil , extracted from premium walnuts grown in the pristine valleys of Kashmir. Made using traditional cold-press methods, this oil retains its natural aroma, nutrients, and rich golden color , delivering unmatched quality and authenticity. Renowned for its high Omega-3 content and powerful antioxidants , Kashmiri walnut oil supports heart health, brain function, and overall wellness. Its light texture and nutty flavor make it ideal for daily consumption, salads, drizzling, and wellness use , while its nourishing properties are also perfect for skin and hair care . 🌰 Why Choose Kashmiri Walnut Oil? 100% pure & cold-pressed Made from premium Kashmiri walnuts Rich in Omega-3 & essential fatty acids No chemicals, additives, or preservatives Suitable for edible, therapeutic & cosmetic use Experience nature’s finest oil— pure, aromatic, and wholesome , straight from Kashmir’s orchards to your home.",
        weightMl: '500ml',
        painPointHeadline: "Brain Food? Try Omega-3 Rich Oil",
        sensoryDescription: "Pour this golden oil with delicate nutty aroma. Cold-pressed from Kashmiri walnuts, it retains nutrients. Drizzle over salads—silky, mild, slightly sweet with earthy undertones.",
        benefits: [
            { icon: "🧠", title: "Brain Health", description: "High omega-3" },
            { icon: "❤️", title: "Heart Support", description: "Cardiovascular wellness" },
            { icon: "🌰", title: "Cold-Pressed", description: "Nutrients preserved" },
            { icon: "✨", title: "Multi-Use", description: "Cook, skin, hair" },
        ],
        images: [
            { type: 'hero', url: '/products/walnut-oil.png', alt: 'Walnut oil' },
        ],
        stockLevel: 'in-stock',
        stockCount: 15,
        trustBadges: ['cold-pressed', 'organic'],
        frequentlyBoughtWith: ['kashmiri-mamra-badam'],
        averageRating: 4.6,
        reviewCount: 42,
    },
    {
        id: 'walnut-with-shells',
        name: 'Walnut with Shells',
        price: 600,
        originalPrice: 700,
        image: '/products/walnut-with-shells.png',
        category: 'Nuts',
        description: "Premium quality Walnut with Shells from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Walnuts (Akhrot) Experience the pure richness of authentic Kashmiri Walnuts , handpicked from the pristine valleys of Kashmir. Naturally grown in the cool Himalayan climate, these walnuts are known for their light color, crisp texture, and superior taste compared to ordinary varieties. Our Kashmiri walnuts are 100% natural, non-GMO, and free from chemicals or preservatives , making them a perfect choice for daily nutrition. Carefully cleaned and packed to retain freshness, every kernel delivers a rich, nutty flavor and powerful health benefits. 🌰 Why Choose Kashmiri Walnuts? Premium quality, naturally grown in Kashmir Rich in Omega-3, antioxidants & essential nutrients Fresh, crunchy, and full-bodied taste Supports brain health, heart health & immunity Ideal for snacking, baking, cooking & gifting Add a handful of Kashmiri walnuts to your daily diet and enjoy nature’s gift of purity, taste, and wellness —straight from Kashmir to your home.",
        weightMl: '1000g',
        painPointHeadline: "Fresh Walnuts? Crack Open Nature's Brain Food",
        sensoryDescription: "These walnuts come naturally protected in their shells, preserving freshness and flavor. Crack one open to reveal the creamy kernel inside—rich, buttery, with that distinctive walnut taste. The shell protection means maximum nutrition preserved until you're ready to enjoy them.",
        benefits: [
            { icon: "🧠", title: "Brain Boost", description: "Omega-3 rich walnuts" },
            { icon: "🥜", title: "Shell-Fresh", description: "Maximum freshness preserved" },
            { icon: "💪", title: "Protein Packed", description: "Complete nutrition" },
            { icon: "✨", title: "Versatile", description: "Snack or cook with" },
        ],
        images: [
            { type: 'hero', url: '/products/walnut-with-shells.png', alt: 'Premium Kashmiri walnuts in shell' },
            { type: 'lifestyle', url: '/products/walnut-with-shells-lifestyle.png', alt: 'Walnuts in natural setting' },
            { type: 'macro', url: '/products/walnut-with-shells-macro.png', alt: 'Close-up of walnut texture' },
        ],
        stockLevel: 'in-stock',
        stockCount: 28,
        trustBadges: ['natural', 'fresh'],
        frequentlyBoughtWith: ['kashmiri-mamra-badam', 'walnut-oil'],
        averageRating: 4.6,
        reviewCount: 35,
    },
    {
        id: 'kashmiri-oud',
        name: 'Kashmiri Oud',
        price: 1699,
        image: '/products/kashmiri-oud.png',
        category: 'Fragrance',
        description: "Premium quality Kashmiri Oud from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Oud (Premium Aromatic Treasure) Kashmiri Oud is a rare and luxurious aromatic essence, treasured for its deep, rich, woody fragrance with subtle earthy and musky undertones. Sourced and refined with utmost care, this premium oud captures the timeless elegance and spiritual depth associated with Kashmir's heritage. Highly valued in traditional perfumery and spiritual rituals, Kashmiri Oud is known for its long-lasting aroma, calming properties, and sophisticated character. Just a small application releases a complex scent that lingers beautifully, making it a symbol of luxury, purity, and tradition. Why Choose Kashmiri Oud? 🌟 Premium-grade, authentic oud fragrance 🌿 Deep woody, earthy & mystical scent 🕯️ Perfect for personal fragrance, meditation & rituals 👑 Luxurious & long-lasting aroma 🚫 Free from synthetic additives Perfect for personal fragrance, spiritual ceremonies, meditation, or gifting, Kashmiri Oud offers an experience of refined luxury and soulful serenity—straight from the heart of Kashmir.",
        weightMl: '7ml',
        painPointHeadline: "Seeking Authentic Fragrance? Experience Kashmir's Mystical Oud",
        sensoryDescription: "Uncap this precious essence and let the deep, mysterious aroma envelop you—woody, earthy, with hints of ancient forests and sacred temples. Unlike synthetic fragrances, this authentic Kashmiri Oud evolves on your skin, revealing different notes throughout the day. The scent is grounding yet uplifting, perfect for meditation or making a lasting impression. A single drop on pulse points lasts for hours, developing a unique signature scent that's unmistakably you.",
        benefits: [
            { icon: "🌟", title: "Authentic Oud", description: "Genuine Kashmiri fragrance essence" },
            { icon: "🕯️", title: "Long-Lasting", description: "12+ hours of rich aroma" },
            { icon: "🌿", title: "Spiritual Depth", description: "Perfect for meditation & rituals" },
            { icon: "👑", title: "Premium Quality", description: "No synthetic additives" },
        ],
        images: [
            { type: 'hero', url: '/products/kashmiri-oud.png', alt: 'Premium Kashmiri Oud fragrance bottle' },
            { type: 'lifestyle', url: '/products/kashmiri-oud-lifestyle.png', alt: 'Kashmiri Oud in traditional setting' },
        ],
        stockLevel: 'in-stock',
        stockCount: 15,
        trustBadges: ['premium-grade', 'authentic', 'long-lasting'],
        frequentlyBoughtWith: ['golden-oud', 'white-oud'],
        averageRating: 4.8,
        reviewCount: 14,
    },
    {
        id: 'herbal-kehwa',
        name: 'Herbal Kehwa',
        price: 899,
        originalPrice: 999,
        image: '/products/herbal-kehwa.png',
        category: 'Tea',
        description: "Premium quality Herbal Kehwa from Jehlum Kesar Co.",
        detailedDescription: "Description Herbal Kehwa (Traditional Kashmiri Herbal Tea) Herbal Kehwa is a soothing and aromatic Kashmiri tea blend, carefully crafted with a selection of premium herbs, spices, and natural ingredients. Rooted in Kashmiri tradition, this wellness tea is known for its calming properties, digestive benefits, and refreshing warmth. Blended with herbs like green tea, cardamom, cinnamon, ginger, and other Ayurvedic ingredients, Herbal Kehwa offers a naturally caffeine-light beverage that energizes the body while relaxing the mind. Its gentle, earthy flavor with hints of spice makes it perfect for daily wellness rituals. Why Choose Herbal Kehwa? 🍃 Traditional Kashmiri herbal blend 🌿 Rich in natural antioxidants & herbs ☕ Supports digestion & boosts immunity 😌 Calming & refreshing 🚫 No artificial flavors or additives Perfect for morning routines, after meals, or evening relaxation, Herbal Kehwa is a warm embrace of nature's purity and Kashmir's timeless tea culture.",
        weightMl: '250g',
        painPointHeadline: "Need Natural Wellness? Sip Kashmir's Healing Herbal Blend",
        sensoryDescription: "Steep this aromatic blend and watch the herbs unfurl, releasing a symphony of earthy, spicy notes. Unlike regular tea, Herbal Kehwa is a wellness ritual—each ingredient carefully selected for its healing properties. The gentle warmth spreads through your body, the subtle spices awaken your senses without overwhelming. Cardamom and cinnamon dance with ginger and herbs, creating a complex yet soothing flavor profile. This is tea as medicine, as meditation, as tradition passed down through generations of Kashmiri healers.",
        benefits: [
            { icon: "🍃", title: "Herbal Wellness", description: "Ayurvedic ingredients for health" },
            { icon: "🌿", title: "Digestive Support", description: "Aids digestion naturally" },
            { icon: "☕", title: "Light Caffeine", description: "Gentle energy without jitters" },
            { icon: "😌", title: "Calming Ritual", description: "Relaxes mind and body" },
        ],
        images: [
            { type: 'hero', url: '/products/herbal-kehwa.png', alt: 'Herbal Kehwa tea blend' },
            { type: 'lifestyle', url: '/products/herbal-kehwa-lifestyle.png', alt: 'Steaming cup of Herbal Kehwa' },
        ],
        stockLevel: 'in-stock',
        stockCount: 42,
        trustBadges: ['traditional-recipe', 'natural-herbs', 'no-additives'],
        frequentlyBoughtWith: ['shahi-kehwa', 'acacia-honey'],
        averageRating: 4.7,
        reviewCount: 28,
    },
    {
        id: 'pecan-nuts',
        name: 'Pecan Nuts',
        price: 1600,
        image: '/products/pecan-nuts.png',
        category: 'Nuts',
        description: "Premium quality Pecan Nuts from Jehlum Kesar Co.",
        detailedDescription: "Description Premium Pecan Nuts Pecan Nuts are delicious, buttery-flavored nuts known for their rich taste, smooth texture, and impressive nutritional profile. Naturally packed with healthy fats, antioxidants, fiber, and essential minerals, pecans are a perfect choice for health-conscious snacking and gourmet cooking. Our premium pecans are carefully selected, cleaned, and packed to ensure maximum freshness and quality. Their naturally sweet, nutty flavor makes them ideal for eating raw, roasting, or adding to desserts, salads, and baked goods. Why Choose Our Pecan Nuts? 🥜 Premium quality, fresh & crunchy 🧈 Rich, buttery flavor 💪 High in healthy fats, antioxidants & nutrients 🌱 Naturally sourced, no additives 🎨 Perfect for snacking, baking & cooking Enjoy Pecan Nuts as a wholesome snack, breakfast topping, or gourmet ingredient—pure taste, pure nutrition, pure indulgence.",
        weightMl: '500g',
        painPointHeadline: "Want Buttery Richness? Discover Premium Pecan Perfection",
        sensoryDescription: "Crack one open and experience why pecans are America's native luxury nut. The flavor is distinctly buttery, almost sweet, with a creamy texture that melts in your mouth. Unlike other nuts, pecans have a subtle sweetness that makes them addictively delicious without any added sugar. These premium pecans are carefully sourced for size and freshness—each one plump, meaty, and full of that characteristic rich flavor. Toast them lightly to intensify the butteriness, or enjoy them raw for a creamy, smooth bite.",
        benefits: [
            { icon: "🧈", title: "Buttery Flavor", description: "Naturally sweet and rich" },
            { icon: "❤️", title: "Heart Healthy", description: "Rich in monounsaturated fats" },
            { icon: "💪", title: "Antioxidant Power", description: "High in vitamin E" },
            { icon: "✨", title: "Premium Grade", description: "Large, fresh nuts" },
        ],
        images: [
            { type: 'hero', url: '/products/pecan-nuts.png', alt: 'Premium Pecan Nuts' },
        ],
        stockLevel: 'in-stock',
        stockCount: 24,
        trustBadges: ['premium-quality', 'natural', 'nutrient-rich'],
        frequentlyBoughtWith: ['kashmiri-mamra-badam', 'mix-dry-fruits'],
        averageRating: 4.7,
        reviewCount: 19,
    },
    {
        id: 'saffron-face-wash',
        name: 'Saffron Face Wash',
        price: 550,
        image: '/products/face-wash.png',
        category: 'Beauty',
        description: "Premium quality Saffron Face Wash from Jehlum Kesar Co.",
        detailedDescription: "Description Saffron Face Wash - Natural Gentle Cleanser Experience the purity of Kashmir with our Kashmiri Face Wash, a gentle yet effective daily cleanser crafted with natural Kashmiri ingredients. Infused with saffron extracts, rose water, and herbal essences, this face wash deeply cleanses while nourishing and brightening your skin. Formulated to remove dirt, oil, and impurities without stripping natural moisture, it leaves your skin feeling fresh, soft, and radiant. Suitable for all skin types, this paraben-free formula respects your skin's natural balance. Key Benefits 🌸 Gentle Daily Cleansing: Removes impurities without drying 🌿 Natural Kashmiri Ingredients: Saffron, rose water & herbal extracts ✨ Brightening Effect: Promotes natural radiance 💧 Hydrating Formula: Maintains skin moisture balance 🚫 Paraben-Free: Safe and gentle for daily use Perfect for morning and evening skincare routines, Kashmiri Face Wash brings the natural beauty secrets of Kashmir to your daily regimen—pure, gentle, and effective.",
        weightMl: '100ml',
        painPointHeadline: "Tired of Harsh Cleansers? Try Nature's Gentle Touch",
        sensoryDescription: "Squeeze a small amount and feel its creamy texture—not too thick, not watery. The subtle fragrance of saffron and roses greets you as you lather. Unlike harsh chemical cleansers, this face wash respects your skin. The foam is gentle yet thorough, lifting away the day's impurities without that tight, stripped feeling. Rinse and feel the difference—your skin is clean but still soft, hydrated, naturally balanced. This is cleansing the Kashmiri way.",
        benefits: [
            { icon: "🌸", title: "Gentle Cleansing", description: "Removes dirt without stripping moisture" },
            { icon: "✨", title: "Natural Brightening", description: "Saffron enhances skin radiance" },
            { icon: "🌿", title: "Herbal Formula", description: "Rose water and natural extracts" },
            { icon: "💧", title: "Hydrating", description: "Maintains moisture balance" },
        ],
        images: [
            { type: 'hero', url: '/products/face-wash.png', alt: 'Saffron Face Wash bottle' },
            { type: 'lifestyle', url: '/products/face-wash-lifestyle.png', alt: 'Saffron Face Wash in use' },
        ],
        stockLevel: 'in-stock',
        stockCount: 45,
        trustBadges: ['paraben-free', 'natural-ingredients', 'gentle-formula'],
        frequentlyBoughtWith: ['saffron-moisturising-lotion', 'saffron-serum'],
        averageRating: 4.6,
        reviewCount: 34,
    },
    {
        id: 'saffron-moisturising-lotion',
        name: 'Saffron Moisturising Lotion',
        price: 615,
        image: '/products/moisturiser-lifestyle.png',
        category: 'Beauty',
        description: "Premium quality Saffron Moisturising Lotion from Jehlum Kesar Co.",
        detailedDescription: "Description Saffron Moisturising Lotion - Deep Hydration & Nourishment Indulge your skin with our Kashmiri Moisturiser, a luxurious daily cream enriched with the finest natural ingredients from Kashmir. Infused with saffron, almond oil, and botanical extracts, this moisturiser delivers deep hydration while promoting skin elasticity and natural glow. Its lightweight, non-greasy formula absorbs quickly, leaving your skin soft, supple, and perfectly moisturized throughout the day. Suitable for all skin types, this cream works to repair, protect, and rejuvenate your skin naturally. Key Benefits 💧 Deep Hydration: Long-lasting moisture for soft, supple skin 🌸 Saffron-Infused: Natural brightening and anti-aging properties 🌿 Lightweight Formula: Non-greasy, fast-absorbing texture ✨ Skin Rejuvenation: Promotes elasticity and natural glow 🛡️ Daily Protection: Shields skin from environmental damage Perfect for daily use, morning and night, Kashmiri Moisturiser brings the nourishing power of Kashmir's natural treasures to your skincare routine—pure luxury in every application.",
        weightMl: '50ml',
        painPointHeadline: "Dry, Dull Skin? Nourish with Kashmiri Botanicals",
        sensoryDescription: "Scoop out a small amount and notice the rich, creamy texture. As you smooth it across your face, it melts into your skin—no greasy residue, just pure absorption. Within moments, you feel the difference: skin that's plump, hydrated, comfortable. The subtle fragrance of saffron and almonds lingers delicately. This isn't just moisture—it's nourishment. By evening, your skin still feels soft, protected, naturally radiant.",
        benefits: [
            { icon: "💧", title: "Deep Moisture Lock", description: "24-hour hydration" },
            { icon: "🌸", title: "Saffron Brightening", description: "Natural radiance boost" },
            { icon: "🌿", title: "Lightweight", description: "Non-greasy absorption" },
            { icon: "✨", title: "Anti-Aging", description: "Promotes skin elasticity" },
        ],
        images: [
            { type: 'hero', url: '/products/moisturiser-lifestyle.png', alt: 'Saffron Moisturising Lotion application' },
            { type: 'lifestyle', url: '/products/moisturiser.png', alt: 'Saffron Moisturising Lotion bottle' },
        ],
        stockLevel: 'in-stock',
        stockCount: 38,
        trustBadges: ['saffron-infused', 'all-natural', 'non-greasy'],
        frequentlyBoughtWith: ['saffron-face-wash', 'saffron-serum'],
        averageRating: 4.7,
        reviewCount: 52,
    },
    {
        id: 'saffron-serum',
        name: 'Kashmiri Saffron Serum',
        price: 1500,
        image: '/products/saffron-serum.png',
        category: 'Beauty',
        description: "Premium quality Kashmiri Saffron Serum from Jehlum Kesar Co.",
        detailedDescription: "Description Kashmiri Saffron Serum - Premium Anti-Aging Treatment Experience the gold standard of skincare with our Kashmiri Saffron Serum, a potent anti-aging elixir infused with pure Kashmiri saffron extract. This concentrated serum delivers powerful antioxidants deep into your skin, targeting fine lines, dark spots, and uneven tone. Enriched with vitamin-rich botanical oils and natural extracts, it promotes cellular renewal, enhances skin luminosity, and provides intensive nourishment. The lightweight, fast-absorbing formula works overnight to reveal brighter, firmer, more youthful-looking skin. Key Benefits ⚡ Intensive Anti-Aging: Targets fine lines and wrinkles ✨ Brightening Power: Reduces dark spots and hyperpigmentation 🌸 Pure Saffron Extract: Rich in antioxidants and vitamins 💎 Cellular Renewal: Promotes skin regeneration 🌿 Lightweight Formula: Fast-absorbing, non-sticky texture Apply 2-3 drops to cleansed skin before moisturizing—morning and night—for visibly transformed, radiant skin. Kashmiri Saffron Serum: where ancient beauty wisdom meets modern skincare science.",
        weightMl: '30ml',
        painPointHeadline: "Fine Lines? Dark Spots? Let Saffron Transform Your Skin",
        sensoryDescription: "Dispense 2-3 drops onto your palm—the serum is golden-amber, incredibly silky. Gently press into your face and feel it absorb instantly, leaving no residue. The subtle, luxurious scent of saffron reminds you this is premium skincare. Within days, notice your skin looking brighter, more even. Within weeks, fine lines soften, dark spots fade. This is the anti-aging secret of Kashmiri royalty, now yours.",
        benefits: [
            { icon: "⚡", title: "Anti-Aging Power", description: "Reduces fine lines & wrinkles" },
            { icon: "✨", title: "Brightening", description: "Fades dark spots & evens tone" },
            { icon: "🌸", title: "Pure Saffron", description: "Concentrated antioxidants" },
            { icon: "💎", title: "Skin Renewal", description: "Promotes cellular regeneration" },
        ],
        images: [
            { type: 'hero', url: '/products/saffron-serum.png', alt: 'Kashmiri Saffron Serum bottle' },
            { type: 'lifestyle', url: '/products/saffron-serum-lifestyle.png', alt: 'Serum application' },
        ],
        stockLevel: 'in-stock',
        stockCount: 28,
        trustBadges: ['anti-aging', 'saffron-extract', 'concentrated-formula'],
        frequentlyBoughtWith: ['saffron-moisturising-lotion', 'saffron-face-wash'],
        averageRating: 4.8,
        reviewCount: 41,
    },
    {
        id: 'noormark-cream',
        name: 'Noormark Cream',
        price: 520,
        image: '/products/noormark-cream.png',
        category: 'Beauty',
        description: "Premium quality Noormark Cream from Jehlum Kesar Co.",
        detailedDescription: "Description Noormark Cream - Natural Blemish & Pigmentation Treatment Noormark Cream is a specialized skincare solution designed to address blemishes, dark spots, and uneven skin tone naturally. Formulated with potent herbal extracts, saffron, and skin-brightening botanicals, this cream works gently yet effectively to reduce the appearance of marks and pigmentation. Regular use helps reveal clearer, more even-toned skin with a natural, healthy glow. Free from harsh chemicals, Noormark Cream is suitable for all skin types and safe for daily use. Key Benefits 🎯 Targets Dark Spots: Reduces blemishes and pigmentation 🌿 Natural Formula: Herbal extracts and saffron 💡 Even Skin Tone: Promotes uniform complexion ✨ Gentle Yet Effective: Safe for sensitive skin 🚫 Chemical-Free: No harsh bleaching agents Apply a thin layer to affected areas twice daily for best results. Noormark Cream: your natural solution for clearer, more confident skin.",
        weightMl: '30g',
        painPointHeadline: "Struggling with Dark Spots? Reveal Clearer Skin Naturally",
        sensoryDescription: "Apply a small amount to the affected area—the cream has a smooth, velvety texture that spreads easily. Unlike harsh chemical treatments, Noormark works gently, respecting your skin's natural balance. The mild herbal scent reassures you of its natural formulation. With consistent use, watch dark spots gradually fade, skin tone becomes more even. Patience rewards you with naturally clearer, more confident skin.",
        benefits: [
            { icon: "🎯", title: "Blemish Reduction", description: "Fades dark spots & marks" },
            { icon: "🌿", title: "Natural Herbs", description: "Gentle botanical formula" },
            { icon: "💡", title: "Even Tone", description: "Promotes uniform complexion" },
            { icon: "✨", title: "Safe Formula", description: "No harsh chemicals" },
        ],
        images: [
            { type: 'hero', url: '/products/noormark-cream.png', alt: 'Noormark Cream tube' },
        ],
        stockLevel: 'in-stock',
        stockCount: 32,
        trustBadges: ['herbal-formula', 'chemical-free', 'gentle-effective'],
        frequentlyBoughtWith: ['saffron-serum', 'saffron-face-wash'],
        averageRating: 4.5,
        reviewCount: 27,
    },
    {
        id: 'raya-saffron-facial-kit',
        name: 'Raya Saffron Facial Kit',
        price: 2490,
        image: '/products/facial-kit.png',
        category: 'Beauty',
        description: "Premium quality Raya Saffron Facial Kit from Jehlum Kesar Co.",
        detailedDescription: "Description Raya Saffron Facial Kit - Complete Professional Spa Treatment at Home Transform your skincare routine with our Raya Saffron Facial Kit, a complete 6-step professional facial treatment infused with the finest natural ingredients from Kashmir. This luxurious kit includes: cleanser, scrub, massage cream, face pack, finishing cream, and serum—everything you need for a salon-quality facial at home. Enriched with saffron, almond, rose extracts, and herbal botanicals, each product works synergistically to cleanse, exfoliate, nourish, and rejuvenate your skin. Experience deep cleansing, improved circulation, enhanced radiance, and a youthful glow. Perfect for all skin types, this kit delivers visible results from the very first use. Kit Contains: 🧼 Step 1: Facial Cleanser - Deep cleansing 🌰 Step 2: Facial Scrub - Gentle exfoliation 💆 Step 3: Massage Cream - Nourishing massage 🌸 Step 4: Face Pack - Tightening & brightening ✨ Step 5: Finishing Cream - Final glow boost 💎 Step 6: Facial Serum - Intensive nourishment How to Use: Follow the 6-step regimen once a week for best results. Each session takes approximately 45-60 minutes. Detailed instructions included. Raya Saffron Facial Kit: Bring the spa home and unveil your skin's natural beauty.",
        weightMl: '6-piece set',
        painPointHeadline: "Want Salon Glow at Home? Complete Facial Kit with Saffron",
        sensoryDescription: "Open the kit and discover six luxurious products, each crafted for a specific step. Start with the cleanser's gentle lather, then the scrub's soft granules that buff away dullness. The massage cream glides effortlessly, transforming your bathroom into a spa. Apply the face pack and feel it tighten, drawing out impurities. Finish with the cream and see your reflection—skin glowing, refreshed, renewed. This is the complete facial experience, Kashmir-style.",
        benefits: [
            { icon: "🧼", title: "Complete 6-Piece", description: "Professional facial at home" },
            { icon: "🌸", title: "Saffron Enriched", description: "All 6 products infused with saffron" },
            { icon: "✨", title: "Visible Results", description: "Radiant glow from first use" },
            { icon: "💆", title: "Spa Experience", description: "Salon-quality treatment" },
        ],
        images: [
            { type: 'hero', url: '/products/facial-kit.png', alt: 'Raya Saffron Facial Kit complete set' },
            { type: 'lifestyle', url: '/products/facial-kit-lifestyle-1.png', alt: 'Raya Saffron Facial Kit products displayed' },
            { type: 'lifestyle', url: '/products/facial-kit-lifestyle-2.png', alt: 'Raya Saffron Facial Kit in use' },
            { type: 'macro', url: '/products/facial-kit-macro.png', alt: 'Close-up of Raya kit products' },
        ],
        stockLevel: 'in-stock',
        stockCount: 22,
        trustBadges: ['complete-kit', 'saffron-infused', 'professional-grade'],
        frequentlyBoughtWith: ['saffron-serum', 'saffron-moisturising-lotion'],
        averageRating: 4.9,
        reviewCount: 38,
    },
    {
        id: 'rajma-dal',
        name: 'Rajma Dal',
        price: 350,
        image: '/products/rajma-dal.png',
        category: 'Food',
        description: "Premium quality Rajma Dal from Jehlum Kesar Co.",
        detailedDescription: "Rajma Dal is premium kidney beans sourced from the finest farms. Rich in protein, fiber, and essential nutrients, our Rajma Dal is carefully cleaned and packed to ensure freshness. Perfect for making authentic North Indian Rajma curry, salads, and wholesome meals.",
        weightMl: '1kg',
        variants: [
            { weight: 1000, price: 350 },
            { weight: 500, price: 175 },
        ],
        stockLevel: 'in-stock',
        stockCount: 50,
        trustBadges: ['premium-quality', 'natural'],
        averageRating: 4.5,
        reviewCount: 15,
    },
    {
        id: 'dried-apple',
        name: 'Dried Apple',
        price: 200,
        image: '/products/dried-apple.png',
        category: 'Nuts',
        description: "Premium quality Dried Apple from Jehlum Kesar Co.",
        detailedDescription: "Dried Apple slices are naturally sweet and nutritious, carefully dehydrated to preserve their flavor and nutrients. Perfect for healthy snacking, baking, or adding to cereals and trail mixes.",
        weightMl: '200g',
        stockLevel: 'in-stock',
        stockCount: 40,
        trustBadges: ['no-preservatives', 'natural'],
        averageRating: 4.4,
        reviewCount: 12,
    },
    {
        id: 'flax-seeds',
        name: 'Flax Seeds',
        price: 800,
        image: '/products/flax-seeds.png',
        category: 'Other',
        description: "Premium quality Flax Seeds from Jehlum Kesar Co.",
        detailedDescription: "Flax Seeds are a superfood rich in omega-3 fatty acids, fiber, and lignans. Perfect for adding to smoothies, yogurt, or baking. Supports heart health and digestion.",
        weightMl: '1kg',
        stockLevel: 'in-stock',
        stockCount: 35,
        trustBadges: ['superfood', 'organic'],
        averageRating: 4.6,
        reviewCount: 20,
    },
    {
        id: 'chia-seeds',
        name: 'Chia Seeds',
        price: 1200,
        image: '/products/chia-seeds.png',
        category: 'Other',
        description: "Premium quality Chia Seeds from Jehlum Kesar Co.",
        detailedDescription: "Chia Seeds are nutrient-dense superfoods packed with omega-3s, protein, and antioxidants. Great for smoothies, puddings, and healthy recipes. Supports energy and wellness.",
        weightMl: '1kg',
        stockLevel: 'in-stock',
        stockCount: 30,
        trustBadges: ['superfood', 'organic'],
        averageRating: 4.7,
        reviewCount: 25,
    },
    {
        id: 'pumpkin-seeds',
        name: 'Pumpkin Seeds',
        price: 1200,
        image: '/products/pumpkin-seeds.png',
        category: 'Other',
        description: "Premium quality Pumpkin Seeds from Jehlum Kesar Co.",
        detailedDescription: "Pumpkin Seeds are crunchy, nutritious seeds rich in magnesium, zinc, and healthy fats. Perfect for snacking, salads, or as a topping. Supports immune health and vitality.",
        weightMl: '1kg',
        stockLevel: 'in-stock',
        stockCount: 28,
        trustBadges: ['natural', 'nutrient-rich'],
        averageRating: 4.5,
        reviewCount: 18,
    },
    {
        id: 'sunflower-seeds',
        name: 'Sunflower Seeds',
        price: 1200,
        image: '/products/sunflower-seeds.png',
        category: 'Other',
        description: "Premium quality Sunflower Seeds from Jehlum Kesar Co.",
        detailedDescription: "Sunflower Seeds are crunchy and delicious, packed with vitamin E, selenium, and healthy fats. Perfect for snacking or adding to your favorite recipes. Supports skin health and immunity.",
        weightMl: '1kg',
        stockLevel: 'in-stock',
        stockCount: 32,
        trustBadges: ['natural', 'vitamin-rich'],
        averageRating: 4.6,
        reviewCount: 22,
    },
    {
        id: 'instant-mix',
        name: 'Instant Mix',
        price: 310,
        image: '/products/instant-mix.png',
        category: 'Food',
        description: "Premium quality Instant Mix from Jehlum Kesar Co.",
        detailedDescription: "Instant Mix is a convenient ready-to-cook blend perfect for quick and delicious meals. Made with premium ingredients and traditional spices for authentic flavor.",
        weightMl: '250g',
        stockLevel: 'in-stock',
        stockCount: 45,
        trustBadges: ['ready-to-cook', 'traditional-recipe'],
        averageRating: 4.3,
        reviewCount: 10,
    },
    {
        id: 'dried-blueberry',
        name: 'Dried Blueberry',
        price: 1400,
        image: '/products/dried-blueberry.png',
        category: 'Nuts',
        description: "Premium quality Dried Blueberry from Jehlum Kesar Co.",
        detailedDescription: "Dried Blueberries are antioxidant-rich superfruits carefully dried to preserve their sweet-tart flavor and nutritional benefits. Perfect for snacking, baking, or adding to cereals and trail mixes.",
        weightMl: '1kg',
        variants: [
            { weight: 1000, price: 1400 },
            { weight: 500, price: 700 },
        ],
        stockLevel: 'in-stock',
        stockCount: 25,
        trustBadges: ['antioxidant-rich', 'superfruit'],
        averageRating: 4.7,
        reviewCount: 28,
    },
    {
        id: 'dried-blackberry',
        name: 'Dried Blackberry',
        price: 1300,
        image: '/products/dried-blackberry.png',
        category: 'Nuts',
        description: "Premium quality Dried Blackberry from Jehlum Kesar Co.",
        detailedDescription: "Dried Blackberries are naturally sweet and packed with vitamins, fiber, and antioxidants. Carefully dried to maintain their rich flavor and nutritional value. Perfect for healthy snacking and recipes.",
        weightMl: '1kg',
        variants: [
            { weight: 1000, price: 1300 },
            { weight: 500, price: 650 },
        ],
        stockLevel: 'in-stock',
        stockCount: 22,
        trustBadges: ['antioxidant-rich', 'vitamin-rich'],
        averageRating: 4.6,
        reviewCount: 24,
    },
    {
        id: 'dried-cranberry',
        name: 'Dried Cranberry',
        price: 1400,
        image: '/products/dried-cranberry.png',
        category: 'Nuts',
        description: "Premium quality Dried Cranberry from Jehlum Kesar Co.",
        detailedDescription: "Dried Cranberries are tangy, sweet, and loaded with antioxidants. Carefully dried to preserve their unique flavor and health benefits. Perfect for snacking, baking, or adding to salads and cereals.",
        weightMl: '1kg',
        variants: [
            { weight: 1000, price: 1400 },
            { weight: 500, price: 700 },
        ],
        stockLevel: 'in-stock',
        stockCount: 30,
        trustBadges: ['antioxidant-rich', 'natural'],
        averageRating: 4.7,
        reviewCount: 26,
    },
    {
        id: 'sidr-honey',
        name: 'Sidr Honey',
        price: 750,
        image: '/products/sidr-honey.png',
        category: 'Honey',
        description: "Premium quality Sidr Honey from Jehlum Kesar Co.",
        detailedDescription: "Sidr Honey is a rare and premium honey known for its rich flavor and therapeutic properties. Sourced from Sidr trees, this honey is pure, natural, and packed with antioxidants and healing benefits.",
        weightMl: '500ml',
        stockLevel: 'in-stock',
        stockCount: 20,
        trustBadges: ['100-pure', 'premium-quality'],
        averageRating: 4.8,
        reviewCount: 32,
    },
    {
        id: 'noormark-walnut-scrub',
        name: 'Noormark Walnut Scrub',
        price: 620,
        image: '/products/noormark-walnut-scrub.png',
        category: 'Beauty',
        description: "Premium quality Noormark Walnut Scrub from Jehlum Kesar Co.",
        detailedDescription: "Noormark Walnut Scrub is a natural exfoliating face scrub enriched with finely ground walnut shells and herbal extracts. Gently removes dead skin cells, unclogs pores, and reveals smoother, brighter skin.",
        weightMl: '100ml',
        stockLevel: 'in-stock',
        stockCount: 35,
        trustBadges: ['natural-ingredients', 'gentle-exfoliant'],
        averageRating: 4.5,
        reviewCount: 18,
    },
    {
        id: 'bringraj-hair-oil',
        name: 'Bringraj Hair Oil',
        price: 525,
        image: '/products/bringraj-hair-oil.png',
        category: 'Beauty',
        description: "Premium quality Bringraj Hair Oil from Jehlum Kesar Co.",
        detailedDescription: "Bringraj Hair Oil is an Ayurvedic hair treatment enriched with Bringraj extracts and natural oils. Promotes hair growth, reduces hair fall, and nourishes the scalp for stronger, healthier hair.",
        weightMl: '200ml',
        stockLevel: 'in-stock',
        stockCount: 28,
        trustBadges: ['ayurvedic', 'natural-oils'],
        averageRating: 4.6,
        reviewCount: 21,
    },
    {
        id: 'muesli',
        name: 'Muesli',
        price: 700,
        image: '/products/muesli.png',
        category: 'Food',
        description: "Premium quality Muesli from Jehlum Kesar Co.",
        detailedDescription: "Muesli is a wholesome breakfast blend of rolled oats, nuts, seeds, and dried fruits. Packed with fiber, protein, and natural energy. Perfect with milk, yogurt, or as a healthy snack.",
        weightMl: '500g',
        stockLevel: 'in-stock',
        stockCount: 40,
        trustBadges: ['wholesome', 'natural'],
        averageRating: 4.5,
        reviewCount: 16,
    },
    {
        id: 'red-chilli-whole',
        name: 'Red Chilli (Whole)',
        price: 1000,
        image: '/products/red-chilli-whole.png',
        category: 'Spices',
        description: "Premium quality Red Chilli (Whole) from Jehlum Kesar Co.",
        detailedDescription: "Red Chilli (Whole) is premium quality dried red chillies perfect for adding heat and flavor to your dishes. Carefully selected and packed to maintain freshness and potency. Essential for authentic Indian cooking.",
        weightMl: '1kg',
        stockLevel: 'in-stock',
        stockCount: 50,
        trustBadges: ['premium-quality', 'natural'],
        averageRating: 4.6,
        reviewCount: 30,
    },
];
