export type ProductVariant = {
    weight: number; // in grams
    price: number;
    originalPrice?: number;
};

export type Product = {
    id: string;
    name: string;
    price: number; // base/starting price
    originalPrice?: number;
    image: string;
    category: string;
    description: string;
    detailedDescription?: string;
    weightMl?: string; // weight or volume (e.g., '500g', '250ml')
    sku?: string;
    variants?: ProductVariant[]; // weight-based variants with prices
};

export const products: Product[] = [
    {
        id: 'choco-almond-rocks',
        name: 'Choco Almond Rocks',
        price: 800,
        originalPrice: 899,
        image: '/products/choco-almond-rocks.png',
        category: 'Nuts',
        description: "Premium quality Choco Almond Rocks from Jehlum Kesar Co.",
        weightMl: '500g',
    },
    {
        id: 'dried-kiwi',
        name: 'Dried Kiwi',
        price: 500,
        originalPrice: 599,
        image: '/products/dried-kiwi.png',
        category: 'Nuts',
        description: "Premium quality Dried Kiwi from Jehlum Kesar Co.",
        weightMl: '500g',
    },
    {
        id: 'cherry',
        name: 'Cherry',
        price: 600,
        originalPrice: 699,
        image: '/products/cherry.png',
        category: 'Nuts',
        description: "Premium quality Cherry from Jehlum Kesar Co.",
        weightMl: '500g',
    },
    {
        id: 'macadamia-nuts-in-shell',
        name: 'Macadamia Nuts In Shell',
        price: 1500,
        originalPrice: 1799,
        image: '/products/macadamia-nuts-in-shell.png',
        category: 'Nuts',
        description: "Premium quality Macadamia Nuts In Shell from Jehlum Kesar Co.",
        weightMl: '400g',
    },
    {
        id: 'beetroot-lip-butter',
        name: 'Beetroot Lip Butter',
        price: 350,
        originalPrice: 399,
        image: '/products/beetroot-lip-butter.png',
        category: 'Beauty',
        description: "Premium quality Beetroot Lip Butter from Jehlum Kesar Co.",
        weightMl: '15ml',
    },
    {
        id: 'rosemary-essential-oil',
        name: 'Rosemary Essential Oil',
        price: 599,
        originalPrice: 699,
        image: '/products/rosemary-essential-oil.png',
        category: 'Beauty',
        description: "Premium quality Rosemary Essential Oil from Jehlum Kesar Co.",
        weightMl: '15ml',
    },
    {
        id: 'saffron-lip-butter',
        name: 'Saffron Lip Butter',
        price: 350,
        originalPrice: 399,
        image: '/products/saffron-lip-butter.png',
        category: 'Beauty',
        description: "Premium quality Saffron Lip Butter from Jehlum Kesar Co.",
        weightMl: '10g',
    },
    {
        id: 'white-oud',
        name: 'White Oud',
        price: 1649,
        originalPrice: 1749,
        image: '/products/white-oud.png',
        category: 'Fragrance',
        description: "Premium quality White Oud from Jehlum Kesar Co.",
        weightMl: '7ml',
    },
    {
        id: 'golden-oud',
        name: 'Golden Oud',
        price: 199,
        originalPrice: 1699,
        image: '/products/golden-oud.png',
        category: 'Fragrance',
        description: "Premium quality Golden Oud from Jehlum Kesar Co.",
        weightMl: '7ml',
    },
    {
        id: 'acacia-honey',
        name: 'Acacia Honey',
        price: 800,
        originalPrice: 850,
        image: '/products/acacia-honey.png',
        category: 'Honey',
        description: "Premium quality Acacia Honey from Jehlum Kesar Co.",
        weightMl: '500ml',
    },
    {
        id: 'gulkhand',
        name: 'Gulkhand',
        price: 400,
        originalPrice: 499,
        image: '/products/gulkhand.webp',
        category: 'Kashmiri Special',
        description: "Premium quality Gulkhand from Jehlum Kesar Co.",
        weightMl: '500g',
    },
    {
        id: 'kashmiri-mamra-badam',
        name: 'Kashmiri Mamra Badam',
        price: 1000,
        image: '/products/kashmiri-mamra-badam.png',
        category: 'Nuts',
        description: "Premium quality Kashmiri Mamra Badam from Jehlum Kesar Co.",
        weightMl: '1kg',
        sku: 'CBM22',
        variants: [
            { weight: 250, price: 1000 },
            { weight: 500, price: 2000 },
        ],
    },
    {
        id: 'kashmiri-saffron',
        name: 'Kashmiri Saffron',
        price: 350,
        image: '/products/kashmiri-saffron.png',
        category: 'Saffron',
        description: "The Red Gold of Kashmir. Indulge in the luxury of authentic Kashmiri Saffron. Unlike other varieties, Kashmiri Kesar is prized for having the highest levels of Crocin (color), Picrocrocin (flavor), and Safranal (aroma). Our saffron is hand-harvested in the autumn chill of the Kashmir Valley. We laboriously separate the deep red stigmas (Mongra) from the flower to ensure you get only the most potent part of the spice.",
        sku: 'CBM21',
        variants: [
            { weight: 1, price: 350 },
            { weight: 2, price: 700 },
            { weight: 5, price: 1750 },
            { weight: 10, price: 3500 },
            { weight: 20, price: 7000 },
            { weight: 25, price: 8750 },
            { weight: 50, price: 17500 },
        ],
    },
    {
        id: 'mix-dry-fruits',
        name: 'Mix Dry Fruits',
        price: 700,
        originalPrice: 800,
        image: '/products/mix-dry-fruits.png',
        category: 'Nuts',
        description: "Premium quality Mix Dry Fruits from Jehlum Kesar Co.",
        weightMl: '500g',
        sku: 'CBM23',
    },
    {
        id: 'rose-water',
        name: 'Rose Water',
        price: 350,
        originalPrice: 399,
        image: '/products/rose-water.webp',
        category: 'Beauty',
        description: "Premium quality Rose Water from Jehlum Kesar Co.",
        weightMl: '200ml',
    },
    {
        id: 'safroon-honey',
        name: 'Safroon Honey',
        price: 800,
        originalPrice: 1000,
        image: '/products/safroon-honey.png',
        category: 'Honey',
        description: "Premium quality Safroon Honey from Jehlum Kesar Co.",
        weightMl: '500g',
    },
    {
        id: 'shahi-heeing',
        name: 'Shahi Heeing',
        price: 599,
        originalPrice: 850,
        image: '/products/shahi-heeing.png',
        category: 'Kashmiri Special',
        description: "Premium quality Shahi Heeing from Jehlum Kesar Co.",
        weightMl: '300g',
    },
    {
        id: 'shahi-kehwa',
        name: 'Shahi Kehwa',
        price: 1000,
        originalPrice: 1099,
        image: '/products/shahi-kehwa.webp',
        category: 'Tea',
        description: "Premium quality Shahi Kehwa from Jehlum Kesar Co.",
        weightMl: '250g',
        sku: 'N/A',
    },
    {
        id: 'shilajit',
        name: 'Shilajit',
        price: 3000,
        originalPrice: 3500,
        image: '/products/shilajit.png',
        category: 'Kashmiri Special',
        description: "Premium quality Shilajit from Jehlum Kesar Co.",
        weightMl: '300g',
    },
    {
        id: 'walnut-oil',
        name: 'Walnut Oil',
        price: 1300,
        originalPrice: 1500,
        image: '/products/walnut-oil.png',
        category: 'Nuts',
        description: "Premium quality Walnut Oil from Jehlum Kesar Co.",
        weightMl: '500ml',
    },
    {
        id: 'walnut-with-shells',
        name: 'Walnut with Shells',
        price: 600,
        originalPrice: 700,
        image: '/products/walnut-with-shells.png',
        category: 'Nuts',
        description: "Premium quality Walnut with Shells from Jehlum Kesar Co.",
        weightMl: '1000g',
    },
];
